# Generated by Django 3.1.3 on 2022-10-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20221004_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='choice',
            new_name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.AddField(
            model_name='choice',
            name='hint',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
