# Generated by Django 3.1.3 on 2022-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20221005_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='hint',
            field=models.CharField(default='', max_length=200),
        ),
    ]
