# Generated by Django 4.1.2 on 2022-10-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20221006_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
        migrations.AddField(
            model_name='submission',
            name='questions',
            field=models.ManyToManyField(to='onlinecourse.question'),
        ),
    ]
